import { Router } from "express";
import crypto from "crypto";
import jwt from "jsonwebtoken";
import { UserModel, ExtensionSessionModel } from "@linkedon/database";
import { HttpErrors } from "../middleware/error.middleware";
import { config } from "../config";
import { authenticate, AuthenticatedRequest } from "../middleware/auth.middleware";

export const extensionRouter = Router();

// POST /extension/auth — Exchange short-lived auth token from web app
extensionRouter.post("/auth", async (req, res) => {
  const { authorizationToken, deviceId } = req.body;
  if (!authorizationToken || !deviceId) {
    throw HttpErrors.badRequest("authorizationToken and deviceId required");
  }

  // Verify the short-lived token generated by web app
  try {
    const payload = jwt.verify(authorizationToken, config.jwtSecret + ":extension") as {
      sub: string;
      type: string;
    };
    if (payload.type !== "extension_auth") throw new Error("Invalid token type");

    const user = await UserModel.findById(payload.sub);
    if (!user) throw HttpErrors.unauthorized("User not found");

    // Generate extension tokens
    const accessToken = jwt.sign(
      { sub: user._id.toString(), email: user.email, type: "extension" },
      config.jwtSecret,
      { expiresIn: "1h" }
    );
    const refreshToken = crypto.randomBytes(32).toString("hex");
    const tokenHash = crypto.createHash("sha256").update(refreshToken).digest("hex");

    await ExtensionSessionModel.create({
      userId: user._id,
      deviceId,
      tokenHash,
      expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000), // 30 days
    });

    res.json({
      success: true,
      data: {
        accessToken,
        refreshToken,
        expiresIn: 3600,
        user: {
          _id: user._id,
          name: user.name,
          email: user.email,
          avatar: user.avatar,
        },
      },
    });
  } catch {
    throw HttpErrors.unauthorized("Invalid authorization token");
  }
});

// GET /extension/token — Generate short-lived extension auth token (called from web app)
extensionRouter.get("/token", authenticate, async (req: AuthenticatedRequest, res) => {
  const token = jwt.sign(
    { sub: req.user!._id, type: "extension_auth" },
    config.jwtSecret + ":extension",
    { expiresIn: "5m" } // 5-minute window to exchange
  );
  res.json({ success: true, data: { token, expiresIn: 300 } });
});

// DELETE /extension/session
extensionRouter.delete("/session", authenticate, async (req: AuthenticatedRequest, res) => {
  const { deviceId } = req.body;
  if (deviceId) {
    await ExtensionSessionModel.deleteOne({ userId: req.user!._id, deviceId });
  } else {
    await ExtensionSessionModel.deleteMany({ userId: req.user!._id });
  }
  res.json({ success: true, data: { message: "Extension session revoked" } });
});
